# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c685236b93d778e67e59808c42f1839e3c0f2b99c00535db127308841aa3e55dd7fae84b87a92dc3457c0c56573ea89eecc18ff63b074bcc2c0de389b3c56d0

test:
  secret_key_base: 97d7726ea04993f04eaf13e7b25e788a28b1c2fc88a730ab6028e742b3c099e3c1800385ce4ba32c14eb55aacdedb2ce235c13ab925338a43895347cbd35d36b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
